export const projectData = [
  {
    id: "1",
    img: "https://github.com/fudge88/foodtopia/raw/main/assets/images/wireframes/index-ss.png",
    live: "https://fudge88.github.io/foodtopia/",
    repo: "https://github.com/fudge88/foodtopia",
    title: "Title 1",
  },
  {
    id: "2",
    img: "https://github.com/fudge88/dating-app/raw/main/public/assets/img/homess.png",
    live: "https://crush-app-2022.herokuapp.com/",
    repo: "https://github.com/fudge88/dating-app",
    title: "Title 1",
  },
  {
    id: "3",
    img: "https://github.com/fudge88/weather-dashoard/raw/main/assets/images/responsive.gif",
    live: "https://github.com/fudge88/weather-dashoard",
    repo: "https://fudge88.github.io/weather-dashoard/",
    title: "Title 1",
  },
  {
    id: "4",
    img: "https://github.com/fudge88/day-planner-app/raw/main/assets/images/app.gif",
    live: "https://fudge88.github.io/day-planner-app/",
    repo: "https://github.com/fudge88/day-planner-app",
    title: "Title 1",
  },
  {
    id: "5",
    img: "https://github.com/fudge88/javascript-multiple-choice-challange/raw/dev/assets/images/quiz-app.gif",
    live: "https://fudge88.github.io/javascript-multiple-choice-challange/",
    repo: "https://github.com/fudge88/javascript-multiple-choice-challange/tree/dev",
    title: "Title 1",
  },
  {
    id: "6",
    img: "https://github.com/fudge88/mvc-blog/raw/dev/public/assets/img/home-readme.png",
    live: "https://mvc-trekking-blog.herokuapp.com/",
    repo: "https://github.com/fudge88/mvc-blog/tree/dev",
    title: "Title 1",
  },
  {
    id: "1",
    img: "https://github.com/fudge88/ecommerce-backend/raw/dev/img/ecom.gif",
    repo: "https://github.com/fudge88/ecommerce-backend/tree/dev",
    title: "Title 1",
  },
  {
    id: "3",
    img: "https://github.com/fudge88/team-profile-generator/raw/dev/dist/assets/questions.gif",
    repo: "https://github.com/fudge88/team-profile-generator/tree/dev",
    title: "Title 1",
  },
  {
    id: "3",
    img: "https://github.com/fudge88/employee-tracker-sql/raw/dev/img/et-demo.gif",
    repo: "https://github.com/fudge88/employee-tracker-sql/tree/dev",
    title: "Title 1",
  },
  {
    id: "4",
    img: "https://github.com/fudge88/social-network-backend/raw/dev/img/postman.gif",
    repo: "https://github.com/fudge88/social-network-backend/tree/dev",
    title: "Title 1",
  },
];
